-- Migration: Create backfill_log table for month-by-month systematic backfill tracking
-- Purpose: Track completion status, metrics, and errors for AI-driven historical book backfill
-- Date: 2026-01-13

-- =================================================================================
-- Backfill Log Table
-- =================================================================================

CREATE TABLE IF NOT EXISTS backfill_log (
  id SERIAL PRIMARY KEY,
  year INT NOT NULL CHECK (year BETWEEN 1900 AND 2100),
  month INT NOT NULL CHECK (month BETWEEN 1 AND 12),
  status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'retry')),

  -- Metrics
  books_generated INT DEFAULT 0 CHECK (books_generated >= 0),
  isbns_resolved INT DEFAULT 0 CHECK (isbns_resolved >= 0),
  resolution_rate DECIMAL(5,2) CHECK (resolution_rate BETWEEN 0 AND 100),
  isbns_queued INT DEFAULT 0 CHECK (isbns_queued >= 0),

  -- API Usage Tracking
  gemini_calls INT DEFAULT 0 CHECK (gemini_calls >= 0),
  xai_calls INT DEFAULT 0 CHECK (xai_calls >= 0),
  isbndb_calls INT DEFAULT 0 CHECK (isbndb_calls >= 0),

  -- Timestamps
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,

  -- Error Handling
  error_message TEXT,
  retry_count INT DEFAULT 0 CHECK (retry_count >= 0 AND retry_count <= 5),
  last_retry_at TIMESTAMP WITH TIME ZONE,

  -- Metadata
  prompt_variant VARCHAR(50) DEFAULT 'baseline',
  batch_size INT DEFAULT 20 CHECK (batch_size BETWEEN 1 AND 100),

  -- Constraints
  UNIQUE(year, month),
  CHECK (isbns_resolved <= books_generated),
  CHECK (isbns_queued <= isbns_resolved),
  CHECK (completed_at IS NULL OR completed_at >= started_at)
);

-- =================================================================================
-- Indexes for Performance
-- =================================================================================

-- Query by status (find pending/failed months)
CREATE INDEX idx_backfill_status ON backfill_log(status);

-- Query by year/month for chronological operations
CREATE INDEX idx_backfill_year_month ON backfill_log(year DESC, month DESC);

-- Query by completion time for recent activity
CREATE INDEX idx_backfill_completed ON backfill_log(completed_at DESC) WHERE completed_at IS NOT NULL;

-- Composite index for scheduler queries (pending months in chronological order)
CREATE INDEX idx_backfill_scheduler ON backfill_log(status, year DESC, month DESC) WHERE status IN ('pending', 'retry', 'failed');

-- =================================================================================
-- Comments for Documentation
-- =================================================================================

COMMENT ON TABLE backfill_log IS 'Tracks systematic month-by-month backfill operations for AI-generated historical book enrichment';
COMMENT ON COLUMN backfill_log.status IS 'Current processing status: pending (not started), processing (in progress), completed (success), failed (error), retry (will retry)';
COMMENT ON COLUMN backfill_log.books_generated IS 'Total books generated by AI providers (Gemini + Grok combined)';
COMMENT ON COLUMN backfill_log.isbns_resolved IS 'Number of ISBNs successfully resolved via ISBNdb/OpenLibrary';
COMMENT ON COLUMN backfill_log.resolution_rate IS 'Percentage of generated books that resolved to valid ISBNs (0-100)';
COMMENT ON COLUMN backfill_log.isbns_queued IS 'Number of ISBNs queued for enrichment pipeline (after deduplication)';
COMMENT ON COLUMN backfill_log.prompt_variant IS 'AI prompt variant used (baseline, contemporary-notable, etc.)';
COMMENT ON COLUMN backfill_log.retry_count IS 'Number of retry attempts (max 5)';

-- =================================================================================
-- Initial State Seeding (Optional)
-- =================================================================================

-- Seed pending months for 2020-2024 (recent-first priority)
-- Uncomment to pre-populate the backfill queue

-- INSERT INTO backfill_log (year, month, status, prompt_variant)
-- SELECT
--   y.year,
--   m.month,
--   'pending'::VARCHAR,
--   CASE WHEN y.year >= 2020 THEN 'contemporary-notable' ELSE 'baseline' END
-- FROM
--   generate_series(2000, 2024) AS y(year)
--   CROSS JOIN generate_series(1, 12) AS m(month)
-- WHERE
--   (y.year < 2024) OR (y.year = 2024 AND m.month <= 12)
-- ORDER BY y.year DESC, m.month DESC
-- ON CONFLICT (year, month) DO NOTHING;
