#!/bin/bash
# Query Gemini Synthetic Books
# Shows all books generated by Gemini backfill (even without ISBNs)

ssh root@Tower.local "docker exec postgres psql -U openlibrary -d openlibrary -c \"
SELECT
  (metadata#>>'{}')::jsonb->>'gemini_source' as source,
  title,
  (metadata#>>'{}')::jsonb->>'gemini_author' as author,
  created_at::date as created
FROM enriched_works
WHERE synthetic = true
  AND primary_provider = 'gemini-backfill'
ORDER BY 1, 2;
\""
